language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"

before_script:
  - npm install -g gulp
  - npm install gulp
script: gulp

deploy:
  provider: s3
  access_key_id: s3_access_key
  secret_access_key: s3_secret
  bucket: "azuqua_static"
  skip_cleanup: true
  upload_dir: docs
